repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v2.3.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: format-rust
        language: system
        entry: cargo fmt
        pass_filenames: false
        always_run: true
      - id: cargo-check
        name: check-rust
        language: system
        entry: cargo check
        pass_filenames: false
        always_run: true
